### ISSUE TITLE
Is palindrom: Shorter version

### ISSUE THREAD

**Issue by sashberd** [gwtw/js-interview-questions#12]
Hey what about such isPalindrom implementation:

```
function isPalindrome(str) {
    str = str.replace(/\W/g, '').toLowerCase();
    return (str === str.split('').reverse().join(''));
}
```

**Comment by Tyriar** [comment]
While that is probably fine in practice, the `isTextPalindrome` implementation is tuned for performance as might be expected in a tech interview, only needing to iterate through n/2 items in the string. Your example does a lot of piping through functions which creates 5 new strings/arrays, all of which are O(n) operations.
